### ISSUE TITLE
2.2 - missing right side of top toolbar - sometimes

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#96] opened 2013-05-17 14:07 UTC
If I click on the new "home" icon (brings up left panel just fine), select accounts (accounts list shows up on RHS (Right Hand Side), the left "home page" is still visible and the "+" (to add an account is not visible/available. I have to click on the "home" icon and close the left to get the add account back.

Acts the same for all other entities/views

This was on both FF on the desktop and the browser in Android on my Samsung tablet

**Comment by jbest84** [comment] 2013-05-17 17:52
@rjledger 
QA was not able to reproduce this issue. Clicking anything in the new global left menu should automatically close it. When the menu is open it should shift the primary view to the right (this will hide the icons, and it is intended). Can you try this on our latest 2.2 build: http://107.21.243.158/mobile-builds/2.2/stable/jenkins-argos-saleslogix-v2.2-37/

**Comment by rjledger** [comment] 2013-05-17 18:09
I’ll give it a shot.

What was happening to me was that the LHS did not “slide back” and was staying open. When that happened the screen was so crowded it became un-workable on the phone.  Hopefully this will not do that.
rjl

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047  (alt: +1  508.809.9513)

**Comment by rjledger** [comment] 2013-05-17 19:31
Anything I click on in the LHS main menu throws an error – Forbidden access – was logged in as admin.

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047  (alt: +1  508.809.9513)

**Comment by jbest84** [comment] 2013-05-17 19:39
@rjledger Try lee. It looks like someone put a password on admin.

**Comment by rjledger** [comment] 2013-05-17 19:53
Tried lee – got in fine.

A couple of things:
    A – you have to open the left panel to log out… we could always log out w/the “bottom menu” on any view/screen..  So if you have it collapsed you need to expand it to log out.

  B – it does automatically “collapse” the LHS when I open a new entity

General comment.. still not convinced this is a good nav option for smartphone (small screens). Wished you folks would have run this by some of us in the community before you went down this path…  It’s great on the desktop and on tablets… I’m going to see if I can develop a custom version for our customers that detects smartphones vrs larger screens and adapts.

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047  (alt: +1  508.809.9513)

**Comment by jbest84** [comment] 2013-05-17 19:55
@rjledger It is the same pattern used in the LinkedIn and Facebook mobile applications (both phone and tablet). The logout was moved to this window because the footer toolbar is now gone. The reason the footer toolbar is gone is because list views now continuously scroll (you no longer need to click the button).

**Comment by rjledger** [comment] 2013-05-17 20:46
Since I’m not a user of the LinkedIn mobile app (get enough of LinnkedIn on my laptop and desktop ;-) and never have had a Facebook account and have zero plans to ever do so…  can’t really comment on the comparison…

However,  because LinkedIn and facebook use this approach it doesn’t mean it’s a good GUI for the “crm” world for field sales, service, etc….

Just my (professional) thoughts.. I’ll be running it pas a few more of our customers next week to get their thoughts as well. Also, as a heavy SalesLogix user (for the past 12+ years – both as a CIO and as a bp.. ) myself.. I find it to not work for me (on my phone).

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047  (alt: +1  508.809.9513)

**Comment by rjledger** [comment] 2013-05-20 19:31
Got to thinking over the weekend and noticed it also (seems to) behave like the kindle reader on the (Samsung Android) tablet (right down to the icon on the top toolbar (left side ;-)

Here's a scenario that I'd like you to consider:
    A - click on the the top (left) icon and the master list/menu displays  (does this now under 2.2)
    B - click on an item/entity in the list (ex: contact(s)) and the Account list.js slides out to the right (does this now under 2.2)
    C - Touch ANYPLACE on the Account list.js and the Account list slides "over" the master menu list (takes full screen) <--- doe not do this now but the kindle reader does this. 

Doing "C" makes the UI a bit smoother and nicer IMHO

**Closed as completed** 2014-07-29 06:27 UTC
